### PR TITLE
Modal Pop Up for Mobile and Desktop

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Completed the Modal Pop Up exercise for Mobile and Desktop versions. Applied Java Script code to the portfolio website.

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @AsimKhan2019   😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors

## Required Changes ♻️

- [x] Popup window feature isn't working. I'm unable to open the popup. Kindly fix this issue.

https://user-images.githubusercontent.com/83048208/173882827-16efe295-b10c-441c-9ed6-954bf09d6fb9.mov



_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@zainsadaqat Thank you for the feedback, but I am seeing that my pop-ups are working. In mobile and desktop versions as well. Are you using any pop-up blocker?

**Comment by AsimKhan2019** [comment]
@zainsadaqat How are you? I hope you are having a wonderful week. Can you please check again with the pop-up? I would appreciate your feedback as early as possible.

**Comment by AsimKhan2019** [comment]
@zainsadaqat I hope you like at the web portfolio again, I viewed the portfolio from both branches and witnessed that the popup modals are displaying. Kindly please update me from your end.

**Comment by AsimKhan2019** [comment]
@zainsadaqat Please view the following video and observe that the pop modals are working for both desktop and mobile. 
https://www.loom.com/share/e3b56a858425434e92a46a76e8915fff

**Comment by AsimKhan2019** [comment]
@zainsadaqat If you could clone the repo on to your computer and try running it, might display the pop modals. It is showing the pop modals in the live demo link as well.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @AsimKhan2019 

Your project is complete! Great job for nailing it  🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ popup works well
✅ popup close icon works perfectly well

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

tufoin

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@tufoinnkuo10 Thank you for the feedback

**Pull request merged**
